### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by cookiedragon234** [Crystallinqq/baldhackcapes#1]
I’m sorry, I must be seeing something wrong or something but from what I can see, and btw I must be wrong cause this simple can’t be, it appears that, I’m not on the capeslist? I’m sure that this is not the case, and if it is it’s erroneous, so you know just clickly add 2790e358-79e6-4fc4-8dee-ef5af78890a6 if you get what I mean 🤫🤭 Kk thx bye

**Comment by Crystallinqq** [comment]
popbob

**Comment by cookiedragon234** [comment]
Yes I am popbob how did you know
